language: python
python:
  - '3.7'

install:
  - 'pip install pipenv'

services:
  - docker

before_script: 'pipenv install docker-compose'

script:
  - 'docker-compose run app sh -c "python manage.py test && flake8"'